//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class larmscafeEntities1 : DbContext
    {
        public larmscafeEntities1()
            : base("name=larmscafeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_balanco_patrimonial> tb_balanco_patrimonial { get; set; }
        public virtual DbSet<tb_cargo> tb_cargo { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_custo> tb_custo { get; set; }
        public virtual DbSet<tb_custo_item> tb_custo_item { get; set; }
        public virtual DbSet<tb_despesa> tb_despesa { get; set; }
        public virtual DbSet<tb_estoque> tb_estoque { get; set; }
        public virtual DbSet<tb_faltas> tb_faltas { get; set; }
        public virtual DbSet<tb_fgts> tb_fgts { get; set; }
        public virtual DbSet<tb_fopag> tb_fopag { get; set; }
        public virtual DbSet<tb_fornecedores> tb_fornecedores { get; set; }
        public virtual DbSet<tb_funcionario> tb_funcionario { get; set; }
        public virtual DbSet<tb_inss> tb_inss { get; set; }
        public virtual DbSet<tb_log> tb_log { get; set; }
        public virtual DbSet<tb_materia_prima> tb_materia_prima { get; set; }
        public virtual DbSet<tb_plano_de_saude> tb_plano_de_saude { get; set; }
        public virtual DbSet<tb_plano_odontologico> tb_plano_odontologico { get; set; }
        public virtual DbSet<tb_produto> tb_produto { get; set; }
        public virtual DbSet<tb_salario_familia> tb_salario_familia { get; set; }
        public virtual DbSet<tb_seguro_vida> tb_seguro_vida { get; set; }
        public virtual DbSet<tb_taxa_vt> tb_taxa_vt { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_vale_alimentacao> tb_vale_alimentacao { get; set; }
        public virtual DbSet<tb_vale_refeicao> tb_vale_refeicao { get; set; }
        public virtual DbSet<tb_vale_transporte> tb_vale_transporte { get; set; }
        public virtual DbSet<tb_venda> tb_venda { get; set; }
        public virtual DbSet<tb_venda_produto> tb_venda_produto { get; set; }
        public virtual DbSet<vw_fluxo_de_caixa> vw_fluxo_de_caixa { get; set; }
    
        public virtual ObjectResult<pc_listar_funcionario_Result> pc_listar_funcionario(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_listar_funcionario_Result>("pc_listar_funcionario", nomeParameter);
        }
    }
}
