//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_balanco_patrimonial
    {
        public int id_balanco_patrimonial { get; set; }
        public string nm_referencia { get; set; }
        public decimal vl_valor { get; set; }
        public System.DateTime dt_data { get; set; }
        public string ds_categoria { get; set; }
    }
}
