//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public int id_cliente { get; set; }
        public string nm_cliente { get; set; }
        public string ds_telefone { get; set; }
        public string ds_endereco { get; set; }
        public System.DateTime dt_primeira_compra { get; set; }
        public bool bt_ativo { get; set; }
        public bool bt_fidelizado { get; set; }
        public string ds_email { get; set; }
    }
}
