//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcionario()
        {
            this.tb_faltas = new HashSet<tb_faltas>();
            this.tb_fopag = new HashSet<tb_fopag>();
            this.tb_usuario = new HashSet<tb_usuario>();
            this.tb_venda = new HashSet<tb_venda>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public System.DateTime dt_demitido { get; set; }
        public decimal vl_inss { get; set; }
        public decimal vl_salario_familia { get; set; }
        public decimal vl_periculosidade { get; set; }
        public decimal vl_insalubridade { get; set; }
        public string nm_empresa { get; set; }
        public System.DateTime dt_adimissao { get; set; }
        public decimal vl_salario_bruto { get; set; }
        public string ds_cpf { get; set; }
        public string ds_endereco { get; set; }
        public string ds_telefone { get; set; }
        public string ds_email { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public int id_seguro_vida { get; set; }
        public int id_plano_de_saude { get; set; }
        public int id_plano_odontologico { get; set; }
        public int id_vale_transporte { get; set; }
        public int id_vale_refeicao { get; set; }
        public int id_vale_alimentacao { get; set; }
        public int id_cargo { get; set; }
    
        public virtual tb_cargo tb_cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_faltas> tb_faltas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fopag> tb_fopag { get; set; }
        public virtual tb_plano_de_saude tb_plano_de_saude { get; set; }
        public virtual tb_plano_odontologico tb_plano_odontologico { get; set; }
        public virtual tb_seguro_vida tb_seguro_vida { get; set; }
        public virtual tb_vale_alimentacao tb_vale_alimentacao { get; set; }
        public virtual tb_vale_refeicao tb_vale_refeicao { get; set; }
        public virtual tb_vale_transporte tb_vale_transporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda> tb_venda { get; set; }
    }
}
