//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fornecedores()
        {
            this.tb_custo = new HashSet<tb_custo>();
        }
    
        public int id_fornecedores { get; set; }
        public string nm_empresa_fornecedor { get; set; }
        public string ds_marca_fornecida { get; set; }
        public string ds_cnpj { get; set; }
        public string ds_telefone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_custo> tb_custo { get; set; }
    }
}
