//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fopag
    {
        public int id_fopag { get; set; }
        public int qt_falta { get; set; }
        public decimal vl_total_desconto { get; set; }
        public int qt_hora_extra { get; set; }
        public decimal vl_adicional_noturno { get; set; }
        public decimal vl_gratificacao { get; set; }
        public decimal vl_plr { get; set; }
        public decimal vl_total_proventos { get; set; }
        public decimal ds_adiantamento_semanal { get; set; }
        public System.DateTime dt_pagamento { get; set; }
        public decimal vl_salario { get; set; }
        public string ds_cnpj { get; set; }
        public decimal vl_fgts { get; set; }
        public Nullable<decimal> vl_ir { get; set; }
        public int id_funcionario { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
