//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inss
    {
        public int id_inss { get; set; }
        public string ds_porcentagem { get; set; }
        public decimal vl_salario_inicial { get; set; }
        public decimal vl_salario_maximo { get; set; }
    }
}
