//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log
    {
        public int id_log { get; set; }
        public System.DateTime dt_entrada { get; set; }
        public string ds_tela { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
