//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_salario_familia
    {
        public int id_salario_familia { get; set; }
        public decimal vl_salario_de { get; set; }
        public decimal vl_salario_ate { get; set; }
        public string vl_valor { get; set; }
    }
}
