//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_venda()
        {
            this.tb_venda_produto = new HashSet<tb_venda_produto>();
        }
    
        public int id_venda { get; set; }
        public Nullable<System.DateTime> dt_venda { get; set; }
        public Nullable<int> qt_parcelas { get; set; }
        public string ds_modo_pagamento { get; set; }
        public Nullable<decimal> vl_total_venda { get; set; }
        public int id_funcionario { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda_produto> tb_venda_produto { get; set; }
    }
}
