//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Larm_s_Café.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fluxo_de_caixa
    {
        public Nullable<System.DateTime> dt_pagamento { get; set; }
        public Nullable<decimal> vl_operacao { get; set; }
        public string tp_operacao { get; set; }
    }
}
